name: Convert and Sync

on:
  # Run if push to `master` branch
  push:
    branches:
      - master
  # Run if action is triggered manually
  workflow_dispatch:

jobs:
  convert-and-sync:
    # Use Ubuntu 22.04 LTS
    runs-on: ubuntu-22.04
    steps:
    # Step I
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.32.2
    # Step II
    - name: Checkout
      uses: actions/checkout@v4
    # Step III
    - name: Convert
      run: deno run --allow-read --allow-write index.ts
    # Step IV
    - name: Sync
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        gist_id: 9926b02da1e6d06a83dd655a2044eac1
        file_path: dist/links.json
        file_type: text

# Authored by KuoHuanHuan.
